/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.64 (Ubuntu)
 * Generated at: 2017-06-29 05:33:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class viewAllBuses_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<title>View Buses:</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<h2>Bus List</h2>\n");
      out.write("\t<table border=\"1\">\n");
      out.write("\t\t<tr>\n");
      out.write("\t\t\t<td>Bus Name</td>\n");
      out.write("\t\t\t<td>Bus Station:</td>\n");
      out.write("\t\t\t<td>Platform:</td>\n");
      out.write("\t\t\t<td>Arrival Time:</td>\n");
      out.write("\t\t\t<td>Edit</td>\n");
      out.write("\t\t\t<td>Delete</td>\n");
      out.write("\t\t</tr>\n");
      out.write("\n");

//StudentDao studentDao=new StudentDao();
//List <Student> allStudentList = studentDao.getAllStudents();
//for (Student student: allStudentList) {

      out.write("\n");
      out.write("\t\t<tr>\n");
      out.write("\t\t\t<td>");
      out.print(//student.getRollNumber() );
      out.write("</td>\n");
      out.write("\n");
      out.write("\t\t\t<td>");
      out.print( //student.getName() );
      out.write("</td>\n");
      out.write("\n");
      out.write("\t\t\t<td>");
      out.print( //student.getAge() );
      out.write("</td>\n");
      out.write("\n");
      out.write("\t\t\t<td>");
      out.print(//student.getCourse() );
      out.write("</td>\n");
      out.write("\t\t\t<td><a href=\"updateBus.jsp?rollNumber=");
      out.print(//student.getRollNumber());
      out.write("\">Edit</a></td>\n");
      out.write("\t\t\t<td><a href=\"deleteBus.jsp?rollNumber=");
      out.print(//student.getRollNumber());
      out.write("\">Delete</a></td>\n");
      out.write("\n");
      out.write("\t\t</tr>\n");

//}

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t</table>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
